{
    'name': ' University Education Management',
    'version': '18.0.1.0.0',
    'category': 'Industries',
    'summary': """This modules helps to manage the university 
     education system""",
    'description': """This module serves as a comprehensive solution for
     efficiently managing the education system of a university enhancing
     its overall functionality and user experience.""",
    'author': 'Mohit Nare',
    'company': '',
    'maintainer': 'Mohit Nare',

    'depends': ['base', 'mail', 'hr_recruitment', 'account', 'website'],
    'data': [
        'security/education_university_management_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/education_university_management_menus.xml',
        'data/online_application_menu_data.xml',
        'data/mail_template_data.xml',
        'data/notice_board_email_template.xml',
        'views/notice_board_views.xml',
        'wizard/application_reject_views.xml',
        'views/res_partner_views.xml',
        'views/fee_category_views.xml',
        'views/account_journal_views.xml',
        'views/fee_types_views.xml',
        'views/fee_structure_views.xml',
        'views/account_move_views.xml',
        'views/timetable_period_views.xml',
        'views/university_exam_type_views.xml',
        'views/university_exam_views.xml',
        'views/exam_valuation_views.xml',
        'views/exam_result_views.xml',
        'views/university_timetable_views.xml',
        'views/timetable_schedule_line_views.xml',
        'views/university_application_views.xml',
        'views/university_attendace_views.xml',
        'views/university_attendance_line_views.xml',
        'views/university_student_views.xml',
        'views/university_document_type_views.xml',
        'views/university_document_views.xml',
        'views/reject_reason_views.xml',
        'views/university_course_views.xml',
        'views/university_department_views.xml',
        'views/university_subject_views.xml',
        'views/university_semester_views.xml',
        'views/university_syllabus_views.xml',
        'views/university_academic_year_views.xml',
        'views/university_batch_views.xml',
        'views/university_faculty_views.xml',
        'views/student_portal_templates.xml',
        'views/online_application_templates.xml',
        'views/school_configuration_views.xml',
        'views/university_grade_views.xml',

    ],
    'demo': ['demo/education_university_management_demo.xml'],
    'assets': {
        'web.assets_frontend': [
            '/education_university_management/static/src/css/web_style.css',
            '/education_university_management/static/src/js/online_application.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
