from . import account_journal
from . import account_move
from . import exam_result
from . import exam_subject_line
from . import exam_valuation
from . import exam_valuation_line
from . import fee_category
from . import fee_structure
from . import fee_structure_line
from . import fee_type
from . import reject_reason
from . import res_partner
from . import results_subject_line
from . import timetable_period
from . import timetable_schedule_line
from . import university_academic_year
from . import university_application
from . import university_attendance
from . import university_attendance_line
from . import university_batch
from . import university_course
from . import university_department
from . import university_document
from . import university_document_type
from . import university_exam
from . import university_exam_type
from . import university_faculty
from . import university_semester
from . import university_student
from . import university_subject
from . import university_syllabus
from . import university_timetable
from . import school_configuration
from . import notice_board
from . import university_grade